// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class AckResponse {

    @JsonProperty("ok")
    public Boolean ok;

    @JsonProperty("message")
    public String message;


    public AckResponse() {}

    public AckResponse ok(Boolean value) { this.ok = value; return this; }

    public AckResponse message(String value) { this.message = value; return this; }

}
