// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class AsyncExecuteResponse {

    @JsonProperty("run_id")
    public String runId;

    @JsonProperty("status")
    public String status;

    @JsonProperty("queued_at")
    public String queuedAt;


    public AsyncExecuteResponse() {}

    public AsyncExecuteResponse runId(String value) { this.runId = value; return this; }

    public AsyncExecuteResponse status(String value) { this.status = value; return this; }

    public AsyncExecuteResponse queuedAt(String value) { this.queuedAt = value; return this; }

}
