// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class AsyncExecuteInput {

    @JsonProperty("workflow_id")
    public String workflowId;

    @JsonProperty("input_data")
    public Map<String, Object> inputData;

    @JsonProperty("callback_url")
    public String callbackUrl;

    @JsonProperty("timeout_ms")
    public Integer timeoutMs;


    public AsyncExecuteInput() {}

    public AsyncExecuteInput workflowId(String value) { this.workflowId = value; return this; }

    public AsyncExecuteInput inputData(Map<String, Object> value) { this.inputData = value; return this; }

    public AsyncExecuteInput callbackUrl(String value) { this.callbackUrl = value; return this; }

    public AsyncExecuteInput timeoutMs(Integer value) { this.timeoutMs = value; return this; }

}
