// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ExecutionFailed {

    @JsonProperty("message")
    public String message;

    @JsonProperty("cause")
    public String cause;


    public ExecutionFailed() {}

    public ExecutionFailed message(String value) { this.message = value; return this; }

    public ExecutionFailed cause(String value) { this.cause = value; return this; }

}
