// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ExecutionMetrics {

    @JsonProperty("run_id")
    public String runId;

    @JsonProperty("total_steps")
    public Integer totalSteps;

    @JsonProperty("completed_steps")
    public Integer completedSteps;

    @JsonProperty("failed_steps")
    public Integer failedSteps;

    @JsonProperty("duration_ms")
    public Integer durationMs;

    @JsonProperty("step_metrics")
    public Map<String, Object> stepMetrics;


    public ExecutionMetrics() {}

    public ExecutionMetrics runId(String value) { this.runId = value; return this; }

    public ExecutionMetrics totalSteps(Integer value) { this.totalSteps = value; return this; }

    public ExecutionMetrics completedSteps(Integer value) { this.completedSteps = value; return this; }

    public ExecutionMetrics failedSteps(Integer value) { this.failedSteps = value; return this; }

    public ExecutionMetrics durationMs(Integer value) { this.durationMs = value; return this; }

    public ExecutionMetrics stepMetrics(Map<String, Object> value) { this.stepMetrics = value; return this; }

}
