// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ExecutionNotComplete {

    @JsonProperty("message")
    public String message;

    @JsonProperty("status")
    public String status;


    public ExecutionNotComplete() {}

    public ExecutionNotComplete message(String value) { this.message = value; return this; }

    public ExecutionNotComplete status(String value) { this.status = value; return this; }

}
