// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class HealthResponse {

    @JsonProperty("status")
    public String status;

    @JsonProperty("instance_id")
    public String instanceId;

    @JsonProperty("timestamp")
    public Long timestamp;

    @JsonProperty("nats")
    public Boolean nats;

    @JsonProperty("routes")
    public RoutesStatus routes;

    @JsonProperty("vex_config")
    public VexConfigStatus vexConfig;


    public HealthResponse() {}

    public HealthResponse status(String value) { this.status = value; return this; }

    public HealthResponse instanceId(String value) { this.instanceId = value; return this; }

    public HealthResponse timestamp(Long value) { this.timestamp = value; return this; }

    public HealthResponse nats(Boolean value) { this.nats = value; return this; }

    public HealthResponse routes(RoutesStatus value) { this.routes = value; return this; }

    public HealthResponse vexConfig(VexConfigStatus value) { this.vexConfig = value; return this; }

}
