// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class HealthResponse {

    @JsonProperty("status")
    public String status;

    @JsonProperty("version")
    public String version;

    @JsonProperty("uptime")
    public Integer uptime;

    @JsonProperty("timestamp")
    public Long timestamp;

    @JsonProperty("nats")
    public ServiceStatus nats;

    @JsonProperty("redis")
    public ServiceStatus redis;


    public HealthResponse() {}

    public HealthResponse status(String value) { this.status = value; return this; }

    public HealthResponse version(String value) { this.version = value; return this; }

    public HealthResponse uptime(Integer value) { this.uptime = value; return this; }

    public HealthResponse timestamp(Long value) { this.timestamp = value; return this; }

    public HealthResponse nats(ServiceStatus value) { this.nats = value; return this; }

    public HealthResponse redis(ServiceStatus value) { this.redis = value; return this; }

}
