// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ListExecutionsResponse {

    @JsonProperty("executions")
    public ExecutionList executions;

    @JsonProperty("total")
    public Integer total;

    @JsonProperty("limit")
    public Integer limit;

    @JsonProperty("offset")
    public Integer offset;


    public ListExecutionsResponse() {}

    public ListExecutionsResponse executions(ExecutionList value) { this.executions = value; return this; }

    public ListExecutionsResponse total(Integer value) { this.total = value; return this; }

    public ListExecutionsResponse limit(Integer value) { this.limit = value; return this; }

    public ListExecutionsResponse offset(Integer value) { this.offset = value; return this; }

}
