// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ListExecutionsInput {

    @JsonProperty("workflow_id")
    public String workflowId;

    @JsonProperty("status")
    public String status;

    @JsonProperty("limit")
    public Integer limit;

    @JsonProperty("offset")
    public Integer offset;


    public ListExecutionsInput() {}

    public ListExecutionsInput workflowId(String value) { this.workflowId = value; return this; }

    public ListExecutionsInput status(String value) { this.status = value; return this; }

    public ListExecutionsInput limit(Integer value) { this.limit = value; return this; }

    public ListExecutionsInput offset(Integer value) { this.offset = value; return this; }

}
