// Code generated by vexctl sdk generate. DO NOT EDIT.
package ai.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class RoutesStatus {

    @JsonProperty("count")
    public Integer count;

    @JsonProperty("last_refreshed")
    public String lastRefreshed;

    @JsonProperty("source")
    public String source;

    public RoutesStatus() {}
}
