// Code generated by vexctl sdk generate. DO NOT EDIT.
package com.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ExecutionResult {

    @JsonProperty("run_id")
    public String runId;

    @JsonProperty("status")
    public String status;

    @JsonProperty("output")
    public Map<String, Object> output;

    @JsonProperty("error")
    public String error;

    @JsonProperty("started_at")
    public String startedAt;

    @JsonProperty("completed_at")
    public String completedAt;

    @JsonProperty("duration_ms")
    public Integer durationMs;


    public ExecutionResult() {}

    public ExecutionResult runId(String value) { this.runId = value; return this; }

    public ExecutionResult status(String value) { this.status = value; return this; }

    public ExecutionResult output(Map<String, Object> value) { this.output = value; return this; }

    public ExecutionResult error(String value) { this.error = value; return this; }

    public ExecutionResult startedAt(String value) { this.startedAt = value; return this; }

    public ExecutionResult completedAt(String value) { this.completedAt = value; return this; }

    public ExecutionResult durationMs(Integer value) { this.durationMs = value; return this; }

}
