// Code generated by vexctl sdk generate. DO NOT EDIT.
package com.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ExecutionStatus {

    @JsonProperty("run_id")
    public String runId;

    @JsonProperty("status")
    public String status;

    @JsonProperty("workflow_id")
    public String workflowId;

    @JsonProperty("started_at")
    public String startedAt;

    @JsonProperty("updated_at")
    public String updatedAt;

    @JsonProperty("current_step")
    public String currentStep;

    @JsonProperty("progress")
    public Integer progress;


    public ExecutionStatus() {}

    public ExecutionStatus runId(String value) { this.runId = value; return this; }

    public ExecutionStatus status(String value) { this.status = value; return this; }

    public ExecutionStatus workflowId(String value) { this.workflowId = value; return this; }

    public ExecutionStatus startedAt(String value) { this.startedAt = value; return this; }

    public ExecutionStatus updatedAt(String value) { this.updatedAt = value; return this; }

    public ExecutionStatus currentStep(String value) { this.currentStep = value; return this; }

    public ExecutionStatus progress(Integer value) { this.progress = value; return this; }

}
