// Code generated by vexctl sdk generate. DO NOT EDIT.
package com.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ExecuteWorkflowInput {

    @JsonProperty("workflow_id")
    public String workflowId;

    @JsonProperty("input_data")
    public Map<String, Object> inputData;

    @JsonProperty("timeout_ms")
    public Integer timeoutMs;


    public ExecuteWorkflowInput() {}

    public ExecuteWorkflowInput workflowId(String value) { this.workflowId = value; return this; }

    public ExecuteWorkflowInput inputData(Map<String, Object> value) { this.inputData = value; return this; }

    public ExecuteWorkflowInput timeoutMs(Integer value) { this.timeoutMs = value; return this; }

}
