// Code generated by vexctl sdk generate. DO NOT EDIT.
package com.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ExecutionNotFound {

    @JsonProperty("message")
    public String message;


    public ExecutionNotFound() {}

    public ExecutionNotFound message(String value) { this.message = value; return this; }

}
