// Code generated by vexctl sdk generate. DO NOT EDIT.
package com.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ListWorkflowsResponse {

    @JsonProperty("workflows")
    public WorkflowList workflows;


    public ListWorkflowsResponse() {}

    public ListWorkflowsResponse workflows(WorkflowList value) { this.workflows = value; return this; }

}
