// Code generated by vexctl sdk generate. DO NOT EDIT.
package com.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class RunIdInput {

    @JsonProperty("run_id")
    public String runId;


    public RunIdInput() {}

    public RunIdInput runId(String value) { this.runId = value; return this; }

}
