// Code generated by vexctl sdk generate. DO NOT EDIT.
package com.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ServiceStatus {

    @JsonProperty("ok")
    public Boolean ok;


    public ServiceStatus() {}

    public ServiceStatus ok(Boolean value) { this.ok = value; return this; }

}
