// Code generated by vexctl sdk generate. DO NOT EDIT.
package com.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class WorkflowIdInput {

    @JsonProperty("workflow_id")
    public String workflowId;


    public WorkflowIdInput() {}

    public WorkflowIdInput workflowId(String value) { this.workflowId = value; return this; }

}
