// Code generated by vexctl sdk generate. DO NOT EDIT.
package com.vextura.uwf_engine.models;

import java.util.ArrayList;

/** Generated list type for WorkflowList. */
public class WorkflowList extends ArrayList<WorkflowInfo> {}
