// Code generated by vexctl sdk generate. DO NOT EDIT.
package com.vextura.uwf_engine.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@JsonIgnoreProperties(ignoreUnknown = true)
public class WorkflowInfo {

    @JsonProperty("id")
    public String id;

    @JsonProperty("name")
    public String name;

    @JsonProperty("version")
    public String version;

    @JsonProperty("description")
    public String description;

    @JsonProperty("created_at")
    public String createdAt;

    @JsonProperty("status")
    public String status;

    @JsonProperty("tenant")
    public String tenant;


    public WorkflowInfo() {}

    public WorkflowInfo id(String value) { this.id = value; return this; }

    public WorkflowInfo name(String value) { this.name = value; return this; }

    public WorkflowInfo version(String value) { this.version = value; return this; }

    public WorkflowInfo description(String value) { this.description = value; return this; }

    public WorkflowInfo createdAt(String value) { this.createdAt = value; return this; }

    public WorkflowInfo status(String value) { this.status = value; return this; }

    public WorkflowInfo tenant(String value) { this.tenant = value; return this; }

}
