// Code generated by vexctl sdk generate. DO NOT EDIT.
// Source: WorkflowEngine v1.2.0
package ai.vextura.uwf_engine;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.DeserializationFeature;
import ai.vextura.uwf_engine.models.*;
import ai.vextura.uwf_engine.runtime.*;

import java.util.List;
import java.util.Map;

/**
 * Generated SDK client for WorkflowEngine.
 * Auth, retry, and transport are handled automatically.
 */
public class UwfEngineClient {

    private final Transport transport;
    private final AuthProvider auth;
    private static final ObjectMapper MAPPER = new ObjectMapper()
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

    /**
     * Create a client backed by RIP endpoint resolution.
     * @param ripUrl vex-config base URL, e.g. http://vex-config:9090
     */
    public UwfEngineClient(String ripUrl, AuthProvider auth) {
        this.transport = new Transport("WorkflowEngine", ripUrl);
        this.auth = auth;
    }

    /**
     * Create a client that calls endpoint directly, bypassing RIP.
     * Useful for local dev and smoke tests.
     */
    public static UwfEngineClient withEndpoint(String endpoint, AuthProvider auth) {
        UwfEngineClient c = new UwfEngineClient(endpoint, auth);
        c.transport.setFixedEndpoint(endpoint);
        return c;
    }

    /** ExecuteWorkflow — POST /api/v1/workflows/{workflowId}/execute */
    public ExecutionResult executeWorkflow(ExecuteWorkflowInput req) {
        RetryPolicy policy = new RetryPolicy(3, 200, 5000, true);
        return RetryPolicy.execute(policy, () -> doExecuteWorkflow(req));
    }

    private ExecutionResult doExecuteWorkflow(ExecuteWorkflowInput req) {
        String token = auth.getToken();
        String path = "/api/v1/workflows/{workflowId}/execute"
            .replace("{workflowId}", req.workflowId);
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("POST", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), ExecutionResult.class);
    }

    /** AsyncExecuteWorkflow — POST /api/v1/workflows/{workflowId}/async-execute */
    public AsyncExecuteResponse asyncExecuteWorkflow(AsyncExecuteInput req) {
        RetryPolicy policy = new RetryPolicy(3, 200, 5000, true);
        return RetryPolicy.execute(policy, () -> doAsyncExecuteWorkflow(req));
    }

    private AsyncExecuteResponse doAsyncExecuteWorkflow(AsyncExecuteInput req) {
        String token = auth.getToken();
        String path = "/api/v1/workflows/{workflowId}/async-execute"
            .replace("{workflowId}", req.workflowId);
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("POST", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), AsyncExecuteResponse.class);
    }

    /** GetExecutionStatus — GET /api/v1/executions/{runId} */
    public ExecutionStatus getExecutionStatus(RunIdInput req) {
        RetryPolicy policy = new RetryPolicy(2, 500, 500, false);
        return RetryPolicy.execute(policy, () -> doGetExecutionStatus(req));
    }

    private ExecutionStatus doGetExecutionStatus(RunIdInput req) {
        String token = auth.getToken();
        String path = "/api/v1/executions/{runId}"
            .replace("{runId}", req.runId);
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("GET", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), ExecutionStatus.class);
    }

    /** GetExecutionResult — GET /api/v1/executions/{runId}/result */
    public ExecutionResult getExecutionResult(RunIdInput req) {
        RetryPolicy policy = new RetryPolicy(2, 500, 500, false);
        return RetryPolicy.execute(policy, () -> doGetExecutionResult(req));
    }

    private ExecutionResult doGetExecutionResult(RunIdInput req) {
        String token = auth.getToken();
        String path = "/api/v1/executions/{runId}/result"
            .replace("{runId}", req.runId);
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("GET", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), ExecutionResult.class);
    }

    /** GetExecutionMetrics — GET /api/v1/executions/{runId}/metrics */
    public ExecutionMetrics getExecutionMetrics(RunIdInput req) {
        return doGetExecutionMetrics(req);
    }

    private ExecutionMetrics doGetExecutionMetrics(RunIdInput req) {
        String token = auth.getToken();
        String path = "/api/v1/executions/{runId}/metrics"
            .replace("{runId}", req.runId);
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("GET", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), ExecutionMetrics.class);
    }

    /** CancelExecution — POST /api/v1/executions/{runId}/cancel */
    public AckResponse cancelExecution(RunIdInput req) {
        return doCancelExecution(req);
    }

    private AckResponse doCancelExecution(RunIdInput req) {
        String token = auth.getToken();
        String path = "/api/v1/executions/{runId}/cancel"
            .replace("{runId}", req.runId);
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("POST", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), AckResponse.class);
    }

    /** PauseExecution — POST /api/v1/executions/{runId}/pause */
    public AckResponse pauseExecution(RunIdInput req) {
        return doPauseExecution(req);
    }

    private AckResponse doPauseExecution(RunIdInput req) {
        String token = auth.getToken();
        String path = "/api/v1/executions/{runId}/pause"
            .replace("{runId}", req.runId);
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("POST", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), AckResponse.class);
    }

    /** ResumeExecution — POST /api/v1/executions/{runId}/resume */
    public AckResponse resumeExecution(RunIdInput req) {
        return doResumeExecution(req);
    }

    private AckResponse doResumeExecution(RunIdInput req) {
        String token = auth.getToken();
        String path = "/api/v1/executions/{runId}/resume"
            .replace("{runId}", req.runId);
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("POST", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), AckResponse.class);
    }

    /** RetryExecution — POST /api/v1/executions/{runId}/retry */
    public AsyncExecuteResponse retryExecution(RunIdInput req) {
        RetryPolicy policy = new RetryPolicy(2, 1000, 1000, false);
        return RetryPolicy.execute(policy, () -> doRetryExecution(req));
    }

    private AsyncExecuteResponse doRetryExecution(RunIdInput req) {
        String token = auth.getToken();
        String path = "/api/v1/executions/{runId}/retry"
            .replace("{runId}", req.runId);
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("POST", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), AsyncExecuteResponse.class);
    }

    /** ListExecutions — GET /api/v1/executions */
    public ListExecutionsResponse listExecutions(ListExecutionsInput req) {
        return doListExecutions(req);
    }

    private ListExecutionsResponse doListExecutions(ListExecutionsInput req) {
        String token = auth.getToken();
        String path = "/api/v1/executions";
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("GET", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), ListExecutionsResponse.class);
    }

    /** ListWorkflows — GET /api/v1/workflows */
    public ListWorkflowsResponse listWorkflows() {
        return doListWorkflows();
    }

    private ListWorkflowsResponse doListWorkflows() {
        String token = auth.getToken();
        String path = "/api/v1/workflows";
        String body = "{}";
        var resp = transport.doRequest("GET", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), ListWorkflowsResponse.class);
    }

    /** GetWorkflow — GET /api/v1/workflows/{workflowId} */
    public WorkflowInfo getWorkflow(WorkflowIdInput req) {
        return doGetWorkflow(req);
    }

    private WorkflowInfo doGetWorkflow(WorkflowIdInput req) {
        String token = auth.getToken();
        String path = "/api/v1/workflows/{workflowId}"
            .replace("{workflowId}", req.workflowId);
        String body = SdkException.toJson(MAPPER, req);
        var resp = transport.doRequest("GET", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), WorkflowInfo.class);
    }

    /** HealthCheck — GET /health */
    public HealthResponse healthCheck() {
        return doHealthCheck();
    }

    private HealthResponse doHealthCheck() {
        String token = auth.getToken();
        String path = "/health";
        String body = "{}";
        var resp = transport.doRequest("GET", path, token, body);
        if (resp.statusCode() >= 400) {
            throw SdkException.fromResponse(resp);
        }
        return SdkException.parseJson(MAPPER, resp.body(), HealthResponse.class);
    }

}
